#!/usr/bin/python3
import subprocess, shlex


def get_ssh(remote):
    ret = subprocess.run(['git', 'remote', 'get-url', '--all', '--push', remote], capture_output=True, text=True, check=True)
    finished = False
    remotes = []
    for remote in ret.stdout.split('\n'):
        assert not finished
        if not remote:
            finished = True
            continue
        remotes.append(remote.split(':', maxsplit=1))
    return remotes


def run_command(cmd, remote):
    first = True
    for target, directory in get_ssh(remote):
        if not first:
            print()
        else:
            first = False

        print(f"{target}:{directory}")
        yield subprocess.run(['ssh', target,
            ';'.join(
                [f"cd {shlex.quote(directory)}", shlex.join(cmd)]
            )
        ])


def _cli(argv):
    import argparse

    parser = argparse.ArgumentParser(
        prog="git run-remote",
        description="runs git commands on a remote",
    )

    parser.add_argument("--shell", action="store_true", help='run an arbitrary command (default runs git)')
    parser.add_argument("remote", nargs=1, help='the remote to act in the scope of')
    parser.add_argument("command", nargs="*", help='the command to run in the specified scope')
    ns = parser.parse_args(argv)
    remote, = ns.remote
    if ns.shell:
        cmd = []
    else:
        cmd = ['git']

    cmd.extend(ns.command)
    failed = False
    for ret in run_command(cmd, remote):
        if not ret.returncode:
            failed = True
    if failed:
        return 1
    else:
        return 0

if __name__ == '__main__':
    import sys

    sys.exit(_cli(sys.argv[1:]))
